name: Build WebAssembly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "pendulum-free" ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.7

    - name: Download lua
      id: lua
      uses: mercury233/action-cache-download-file@0e2b8bab566270adae95bd3cd298744402b667eb
      with:
        url: https://www.lua.org/ftp/lua-5.4.8.tar.gz

    - name: Lua
      run: |
        tar -xzf ${{ steps.lua.outputs.filepath }}
        mv lua-5.4.8 lua
        cp premake/lua.lua lua/premake5.lua

    - name: Download sqlite
      id: sqlite
      uses: mercury233/action-cache-download-file@0e2b8bab566270adae95bd3cd298744402b667eb
      with:
        url: https://www.sqlite.org/2026/sqlite-autoconf-3510300.tar.gz

    - name: SQLite
      run: |
        tar -xzf ${{ steps.sqlite.outputs.filepath }}
        mv sqlite-autoconf-3510300 sqlite3

    - name: Download premake
      id: premake
      uses: mercury233/action-cache-download-file@0e2b8bab566270adae95bd3cd298744402b667eb
      with:
        url: https://github.com/premake/premake-core/releases/download/v5.0.0-beta7/premake-5.0.0-beta7-linux.tar.gz

    - name: Premake
      run: |
        mkdir premake-5
        tar -C premake-5 -xzf ${{ steps.premake.outputs.filepath }}
        cp premake/dll.lua dll.lua
        chmod +x premake-5/premake5
        ./premake-5/premake5 gmake --file=dll.lua --os=emscripten --sqlite3-dir=sqlite3

    - name: Build wasm_cjs
      run: |
        cd build
        emmake make -j $(nproc) config=release_wasm_cjs
        cd ..
        mkdir -p dist/wasm_cjs
        cp build/bin/wasm_cjs/Release/libocgcore.* dist/wasm_cjs/
        cp build/bin/wasm_cjs/Release/libsqlite3.* dist/wasm_cjs/ || true

    - name: Upload wasm_cjs artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ocgcore-wasm-cjs
        path: dist/wasm_cjs

  create-release:
    needs: [build-wasm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Create release-latest
        run: |
          cd build
          cd ocgcore-wasm-cjs
          zip -r ../ocgcore-wasm-cjs.zip ./*
          cd ..
          gh release delete wasm-latest --cleanup-tag -y || true
          gh release create wasm-latest $(find . -type f -name "*.zip") \
            --target "$GITHUB_SHA" \
            --title "wasm-latest" \
            --notes "Latest wasm for ${{ github.ref_name }}" \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push-to-server:
    needs: [build-wasm]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: build

    - name: Deploy to Server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:
        username: ${{ secrets.SSH_USER }}
        server: ${{ secrets.SSH_SERVER }}
        port: 22
        local_path: './build/ocgcore-wasm-cjs/*'
        remote_path: ${{ secrets.SSH_PATH }}
        sftp_only: true
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
